import type { DashboardStats, Lead } from "./types";

export const MOCK_STATS: DashboardStats = {
  totalIntakes: 214,
  hotLeadsThisWeek: 12,
  conversionRatePct: 31.4,
  avgTimeToReviewMinutes: 47,
};

export const MOCK_LEADS: Lead[] = [
  {
    id: "lead_1001",
    clientFirstName: "Maria",
    clientLastName: "Delgado",
    clientPhone: "3055551234",
    clientEmail: "maria.delgado@example.com",
    practiceArea: "Motor Vehicle Accident",
    jurisdictionState: "FL",
    incidentDate: "2026-07-02",
    dateIngested: "2026-08-18T14:22:00Z",
    injurySeverity: "HOSPITALIZED",
    currentlyRepresented: false,
    scoreStatus: "HOT",
    confidenceScore: 0.93,
    summaryOfFacts:
      "Client was rear-ended while stopped at a red light on I-95. Police report cites the other driver for following too closely. Client was transported by ambulance and admitted overnight for observation of a suspected concussion and a fractured wrist.",
    rationale: [
      "Police report assigns clear fault to the other driver.",
      "Hospital admission establishes documented, significant damages.",
      "No competing representation or eligibility issues identified.",
    ],
    solStatus: "Within Limit",
    syncedToClio: false,
    dismissed: false,
    transcript: [
      {
        id: "t1",
        speaker: "ai",
        content: "Hi Maria, I'm so sorry to hear about your accident. Can you tell me the date and location of the incident?",
        timestamp: "2026-08-18T14:10:00Z",
      },
      {
        id: "t2",
        speaker: "client",
        content: "It happened July 2nd on I-95 near exit 12 in Miami. I was stopped at a red light and got rear-ended.",
        timestamp: "2026-08-18T14:11:20Z",
      },
      {
        id: "t3",
        speaker: "ai",
        content: "Thank you for sharing that. Were you or anyone else injured? If so, did you receive any medical treatment?",
        timestamp: "2026-08-18T14:12:05Z",
      },
      {
        id: "t4",
        speaker: "client",
        content: "Yes, I was taken by ambulance to the ER and admitted overnight. They think I have a concussion and my wrist is fractured.",
        timestamp: "2026-08-18T14:13:40Z",
      },
      {
        id: "t5",
        speaker: "ai",
        content: "I'm glad you got care right away. Do you currently have an attorney representing you for this incident?",
        timestamp: "2026-08-18T14:14:10Z",
      },
      {
        id: "t6",
        speaker: "client",
        content: "No, not yet. This is the first firm I've contacted.",
        timestamp: "2026-08-18T14:14:55Z",
      },
    ],
  },
  {
    id: "lead_1002",
    clientFirstName: "James",
    clientLastName: "Okafor",
    clientPhone: "4045557890",
    clientEmail: "j.okafor@example.com",
    practiceArea: "Premises Liability",
    jurisdictionState: "GA",
    incidentDate: "2026-06-14",
    dateIngested: "2026-08-17T09:05:00Z",
    injurySeverity: "MINOR",
    currentlyRepresented: false,
    scoreStatus: "WARM",
    confidenceScore: 0.61,
    summaryOfFacts:
      "Client slipped on an unmarked wet floor near the entrance of a grocery store. Sustained bruising and a sprained ankle. No witnesses identified yet and it is unclear whether the store had actual or constructive notice of the spill.",
    rationale: [
      "Liability is plausible but notice of the hazard is not yet established.",
      "Injuries are real but relatively minor, limiting damages upside.",
      "Additional investigation (surveillance footage, incident report) is needed.",
    ],
    solStatus: "Within Limit",
    syncedToClio: false,
    dismissed: false,
    transcript: [
      {
        id: "t1",
        speaker: "ai",
        content: "Hi James, thanks for reaching out. Can you walk me through what happened and where?",
        timestamp: "2026-08-17T08:58:00Z",
      },
      {
        id: "t2",
        speaker: "client",
        content: "I slipped on a wet floor at the Kroger on Ponce de Leon. There was no sign or cone anywhere.",
        timestamp: "2026-08-17T08:59:30Z",
      },
      {
        id: "t3",
        speaker: "ai",
        content: "Got it. Did you seek any medical treatment for your injuries?",
        timestamp: "2026-08-17T09:00:10Z",
      },
      {
        id: "t4",
        speaker: "client",
        content: "I went to urgent care for a sprained ankle and some bruising. Nothing broken.",
        timestamp: "2026-08-17T09:01:45Z",
      },
    ],
  },
  {
    id: "lead_1003",
    clientFirstName: "Priya",
    clientLastName: "Nair",
    clientPhone: "6175553456",
    clientEmail: "priya.nair@example.com",
    practiceArea: "Motor Vehicle Accident",
    jurisdictionState: "MA",
    incidentDate: "2023-03-11",
    dateIngested: "2026-08-16T18:40:00Z",
    injurySeverity: "SEVERE",
    currentlyRepresented: false,
    scoreStatus: "COLD",
    confidenceScore: 1.0,
    summaryOfFacts:
      "Client describes a T-bone collision at an intersection with significant injuries requiring physical therapy. Incident occurred more than three years ago, outside the firm's statute-of-limitations window.",
    rationale: [
      "Incident occurred outside the applicable statute of limitations.",
      "Case is time-barred regardless of liability or injury severity.",
      "Not viable to pursue.",
    ],
    solStatus: "Expired",
    syncedToClio: false,
    dismissed: false,
    transcript: [
      {
        id: "t1",
        speaker: "ai",
        content: "Hi Priya, can you tell me when and where the accident occurred?",
        timestamp: "2026-08-16T18:35:00Z",
      },
      {
        id: "t2",
        speaker: "client",
        content: "It was back in March 2023, at an intersection near Kendall Square. I was T-boned.",
        timestamp: "2026-08-16T18:36:15Z",
      },
    ],
  },
  {
    id: "lead_1004",
    clientFirstName: "Deshawn",
    clientLastName: "Carter",
    clientPhone: "3125552211",
    clientEmail: "d.carter@example.com",
    practiceArea: "Motor Vehicle Accident",
    jurisdictionState: "IL",
    incidentDate: "2026-08-01",
    dateIngested: "2026-08-18T11:12:00Z",
    injurySeverity: "SEVERE",
    currentlyRepresented: true,
    scoreStatus: "COLD",
    confidenceScore: 1.0,
    summaryOfFacts:
      "Client reports a serious multi-vehicle collision on I-90 with a herniated disc diagnosis, but confirmed they signed a retainer with another firm two weeks ago.",
    rationale: [
      "Caller is already represented by another attorney for this matter.",
      "Soliciting a represented party raises professional conduct concerns.",
      "Case is disqualified regardless of merits.",
    ],
    solStatus: "Within Limit",
    syncedToClio: false,
    dismissed: true,
    transcript: [
      {
        id: "t1",
        speaker: "ai",
        content: "Hi Deshawn, I'm sorry to hear about the crash. Do you currently have an attorney helping you with this?",
        timestamp: "2026-08-18T11:08:00Z",
      },
      {
        id: "t2",
        speaker: "client",
        content: "Yeah, actually I signed with another firm about two weeks ago, but wanted a second opinion.",
        timestamp: "2026-08-18T11:09:40Z",
      },
    ],
  },
  {
    id: "lead_1005",
    clientFirstName: "Anne",
    clientLastName: "Kowalski",
    clientPhone: "2145559988",
    clientEmail: "anne.kowalski@example.com",
    practiceArea: "Dog Bite",
    jurisdictionState: "TX",
    incidentDate: "2026-08-10",
    dateIngested: "2026-08-18T16:02:00Z",
    injurySeverity: "MINOR",
    currentlyRepresented: false,
    scoreStatus: "HOT",
    confidenceScore: 0.84,
    summaryOfFacts:
      "Client was bitten by a neighbor's dog with a documented prior bite history, requiring stitches and a course of antibiotics. Texas is a strict-liability state for owners with knowledge of prior aggression.",
    rationale: [
      "Owner's prior-bite knowledge supports a strong strict-liability claim.",
      "Injury is documented with stitches and medical records.",
      "Facts are clear and well-corroborated by the client's account.",
    ],
    solStatus: "Within Limit",
    syncedToClio: false,
    dismissed: false,
    transcript: [
      {
        id: "t1",
        speaker: "ai",
        content: "Hi Anne, that sounds painful. Can you tell me when and where the bite happened?",
        timestamp: "2026-08-18T15:55:00Z",
      },
      {
        id: "t2",
        speaker: "client",
        content: "It was August 10th, in my neighbor's front yard. Their dog has bitten someone before, I know because animal control was called last year too.",
        timestamp: "2026-08-18T15:57:10Z",
      },
      {
        id: "t3",
        speaker: "ai",
        content: "That prior history is important. Did you receive medical treatment for the bite?",
        timestamp: "2026-08-18T15:57:50Z",
      },
      {
        id: "t4",
        speaker: "client",
        content: "Yes, I needed 6 stitches and I'm on antibiotics now.",
        timestamp: "2026-08-18T15:58:30Z",
      },
    ],
  },
  {
    id: "lead_1006",
    clientFirstName: "Tobias",
    clientLastName: "Reyes",
    clientPhone: "6025554477",
    clientEmail: "tobias.reyes@example.com",
    practiceArea: "Workplace Injury",
    jurisdictionState: "AZ",
    incidentDate: "2026-05-22",
    dateIngested: "2026-08-15T13:30:00Z",
    injurySeverity: "MINOR",
    currentlyRepresented: false,
    scoreStatus: "WARM",
    confidenceScore: 0.58,
    summaryOfFacts:
      "Client strained his back lifting a pallet at a warehouse. Already filed a workers' comp claim through his employer; unclear if there is a viable third-party liability angle involving faulty equipment.",
    rationale: [
      "Primary remedy likely runs through workers' compensation, not a PI claim.",
      "Possible third-party equipment defect angle needs further review.",
      "Financial upside outside of workers' comp is uncertain at this stage.",
    ],
    solStatus: "Within Limit",
    syncedToClio: false,
    dismissed: false,
    transcript: [
      {
        id: "t1",
        speaker: "ai",
        content: "Hi Tobias, thanks for calling in. Can you describe what happened at work?",
        timestamp: "2026-08-15T13:22:00Z",
      },
      {
        id: "t2",
        speaker: "client",
        content: "I was lifting a pallet and the strap on the pallet jack snapped, and I threw my back out trying to catch it.",
        timestamp: "2026-08-15T13:24:15Z",
      },
    ],
  },
  {
    id: "lead_1007",
    clientFirstName: "Grace",
    clientLastName: "Whitfield",
    clientPhone: "7135552299",
    clientEmail: "grace.whitfield@example.com",
    practiceArea: "Motor Vehicle Accident",
    jurisdictionState: "TX",
    incidentDate: "2026-08-05",
    dateIngested: "2026-08-19T08:45:00Z",
    injurySeverity: "NONE",
    currentlyRepresented: false,
    scoreStatus: "COLD",
    confidenceScore: 1.0,
    summaryOfFacts:
      "Client was involved in a low-speed parking lot fender bender. No injuries were reported by either party, only minor cosmetic vehicle damage.",
    rationale: [
      "No injury was reported.",
      "Personal injury claims require a compensable injury to have value.",
      "Case does not meet baseline eligibility for this practice area.",
    ],
    solStatus: "Within Limit",
    syncedToClio: false,
    dismissed: false,
    transcript: [
      {
        id: "t1",
        speaker: "ai",
        content: "Hi Grace, can you tell me a bit about what happened?",
        timestamp: "2026-08-19T08:40:00Z",
      },
      {
        id: "t2",
        speaker: "client",
        content: "Someone backed into my car in a parking lot. Just some scratches, nobody was hurt.",
        timestamp: "2026-08-19T08:41:30Z",
      },
    ],
  },
  {
    id: "lead_1008",
    clientFirstName: "Marcus",
    clientLastName: "Bellweather",
    clientPhone: "2065553321",
    clientEmail: "marcus.b@example.com",
    practiceArea: "Motor Vehicle Accident",
    jurisdictionState: "WA",
    incidentDate: "2026-07-28",
    dateIngested: "2026-08-19T07:15:00Z",
    injurySeverity: "SEVERE",
    currentlyRepresented: false,
    scoreStatus: "HOT",
    confidenceScore: 0.88,
    summaryOfFacts:
      "Client was struck by a delivery truck that ran a stop sign, resulting in a fractured femur requiring surgery. Dashcam footage from client's vehicle captured the collision clearly.",
    rationale: [
      "Dashcam footage provides strong, clear liability evidence.",
      "Surgical intervention establishes substantial documented damages.",
      "Commercial vehicle involvement raises potential for a well-insured defendant.",
    ],
    solStatus: "Within Limit",
    syncedToClio: true,
    dismissed: false,
    transcript: [
      {
        id: "t1",
        speaker: "ai",
        content: "Hi Marcus, I'm sorry to hear about the crash. Can you tell me what happened?",
        timestamp: "2026-08-19T07:05:00Z",
      },
      {
        id: "t2",
        speaker: "client",
        content: "A delivery truck blew through a stop sign and hit my driver side. I have it on my dashcam.",
        timestamp: "2026-08-19T07:07:20Z",
      },
      {
        id: "t3",
        speaker: "ai",
        content: "That footage will be very helpful. Were you injured, and did you receive treatment?",
        timestamp: "2026-08-19T07:08:00Z",
      },
      {
        id: "t4",
        speaker: "client",
        content: "I fractured my femur and had surgery two days ago. I'm still in the hospital.",
        timestamp: "2026-08-19T07:09:45Z",
      },
    ],
  },
];
